[package]
name = "deltaforge-registry"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
serde_json.workspace = true
tracing.workspace = true
deltaforge-core = {path = "../deltaforge-core"}
