apiVersion: deltaforge/v1
kind: Pipeline
metadata:
  name: mysql-smoke
  tenant: acme

spec:
  source:
    type: mysql
    config:
      id: mysql-shop
      dsn: "mysql://df:dfpw@127.0.0.1:3306"
      tables: ["orders.order_items", "orders.orders"]

  processors:
    - type: javascript
      id: js-normalize
      inline: |
        function processBatch(events) {
          return events.map(event => {
            event.tags = (event.tags || []).concat(["normalized"]);
            return event;
          });
        }

  sinks:
    # Redis: Native envelope for efficiency
    - type: redis
      config:
        id: r1
        uri: "redis://127.0.0.1:6379"
        stream: df.events
        envelope:
          type: native
        encoding: json
        required: false

    # Kafka: Debezium envelope for ecosystem compatibility
    - type: kafka
      config:
        id: kafka
        brokers: "127.0.0.1:9092"
        topic: orders
        envelope:
          type: debezium
        encoding: json
        required: true
        exactly_once: false

  batch:
    max_events: 100
    max_bytes: 8388608
    max_ms: 100
    respect_source_tx: true
    max_inflight: 1

  commit_policy:
    mode: required

  schema_sensing:
    enabled: true
    deep_inspect:
      enabled: true
      max_depth: 5
      max_sample_size: 10
    sampling:
      warmup_events: 2
      sample_rate: 2
      structure_cache: true
      structure_cache_size: 100