apiVersion: deltaforge/v1
kind: Pipeline
metadata:
  name: df-mysql-simple
  tenant: acme

spec:
  source:
    type: mysql
    config:
      id: mysql-shop
      dsn: "mysql://df:dfpw@127.0.0.1:3306"
      tables: ["orders.order_items", "orders.orders"]

  processors: []

  sinks:
    - type: redis
      config:
        id: r1
        uri: "redis://127.0.0.1:6379"
        stream: df.events
        # envelope: native (default)
        # encoding: json (default)
        required: false

    - type: kafka
      config:
        id: kafka
        brokers: "127.0.0.1:9092"
        topic: orders
        # envelope: native (default)
        # encoding: json (default)
        required: true
        exactly_once: false

  batch:
    max_events: 100
    max_bytes: 8388608
    max_ms: 200
    respect_source_tx: true
    max_inflight: 1

  commit_policy:
    mode: required

  schema_sensing:
    enabled: false