apiVersion: v1
kind: Service
metadata:
  name: {{ include "deltaforge.fullname" . }}
  labels:
    {{- include "deltaforge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: api
      port: {{ .Values.service.apiPort }}
      targetPort: api
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "deltaforge.selectorLabels" . | nindent 4 }}
