[package]
name = "deltaforge-metrics"
version = "0.1.0"
edition.workspace = true

[dependencies]
metrics.workspace = true
metrics-exporter-prometheus.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
